import { WineMaster } from "../types";

export const MASTER_WINES: WineMaster[] = [
  {
    id: "9095472",
    name_jp: "パスカルトソ スパークリング",
    name_en: "Pascual Toso Sparkling Brut",
    country: "アルゼンチン",
    region: "メンドーサ",
    grape: "シャルドネ",
    color: "泡",
    type: "辛口",
    vintage: "NV",
    alcohol: "11.5",
    price_bottle: 0,
    price_glass: 0,
    cost: 1800,
    stock: 0,
    ideal_stock: 0,
    supplier: "",
    storage: "",
    ai_explanation: "標高の高いメンドーサの自社畑で収穫されたシャルドネを使用。キリッとした柑橘の酸味と、瓶内二次熟成を思わせるトーストの香ばしさが調和した、非常にクリーンで爽快なスパークリングです。",
    menu_short: "繊細な泡立ちと澄んだ酸味。お食事を華やかに引き立てる辛口泡。",
    pairing: "お刺身（白身）、真鯛のカルパッチョ、天ぷら（塩）",
    sweetness: 1,
    body: 2,
    acidity: 4,
    tannins: 1,
    aroma_intensity: 3,
    complexity: 3,
    finish: 3,
    oak: 1,
    aroma_features: "レモンピール、青リンゴ、焼きたてのパン",
    tags: "爽快, 乾杯の定番, 清涼感",
    best_drinking: "2026",
    image_url: "https://drive.google.com/thumbnail?id=1tVZXXAQZKrpcFrTS9hBP9CeBrvhwtoTh&sz=w1200",
    visible: true
  },
  {
    id: "9293333",
    name_jp: "パスカルトソ CS レゼルヴァ",
    name_en: "Pascual Toso Cabernet Sauvignon Reserva",
    country: "アルゼンチン",
    region: "メンドーサ",
    grape: "CS",
    color: "赤",
    type: "フル",
    vintage: "2020",
    alcohol: "14",
    price_bottle: 0,
    price_glass: 0,
    cost: 3200,
    stock: 0,
    ideal_stock: 0,
    supplier: "",
    storage: "",
    ai_explanation: "アンデスの冷涼な風と豊かな陽光が育んだ、凝縮感溢れるカベルネ。12ヶ月の樽熟成を経て、熟したブラックベリーにバニラやスパイスの複雑な香りが溶け込み、エレガントな余韻が長く続きます。",
    menu_short: "熟したベリーとバニラの優雅な共演。格別の満足感をもたらすフルボディ赤。",
    pairing: "牛ヒレ肉のステーキ、鹿肉のロースト、熟成ハードチーズ",
    sweetness: 1,
    body: 4,
    acidity: 3,
    tannins: 4,
    aroma_intensity: 4,
    complexity: 4,
    finish: 4,
    oak: 4,
    aroma_features: "カシス、ブラックベリー、バニラ、タバコ",
    tags: "ラグジュアリー, 重厚, バニラ香",
    best_drinking: "2028",
    image_url: "https://drive.google.com/thumbnail?id=1NqsLW2lBL0jj7RqldJHDUaS9hEu_2xm_&sz=w1200",
    visible: true
  },
  {
    id: "9308180",
    name_jp: "パスカルトソ ブリュット ロゼ",
    name_en: "Pascual Toso Brut Rose",
    country: "アルゼンチン",
    region: "メンドーサ",
    grape: "CH/MA",
    color: "泡",
    type: "辛口",
    vintage: "NV",
    alcohol: "11.5",
    price_bottle: 0,
    price_glass: 0,
    cost: 2000,
    stock: 0,
    ideal_stock: 0,
    supplier: "",
    storage: "",
    ai_explanation: "シャルドネの気品とマルベックの華やかさが見事に融合。愛らしいサーモンピンクの色彩に、摘みたてのベリーや桃を思わせるアロマが広がります。きめ細やかな泡が喉を潤す、贅沢なロゼスパークリングです。",
    menu_short: "心躍るピンクの輝き。フレッシュな果実味溢れる、エレガントなロゼ。",
    pairing: "海老のチリソース、スモークサーモン、フルーツタルト",
    sweetness: 1,
    body: 2,
    acidity: 4,
    tannins: 1,
    aroma_intensity: 3,
    complexity: 3,
    finish: 3,
    oak: 1,
    aroma_features: "ワイルドベリー、桃、バラの花びら",
    tags: "華やか, お祝い, フルーティー",
    best_drinking: "2026",
    image_url: "https://drive.google.com/thumbnail?id=1gNEL0jsqJSj_zeT9ZeJOxFsYEsJSS14v&sz=w1200",
    visible: true
  },
  {
    id: "9308883",
    name_jp: "バランカス・トソ",
    name_en: "Barrancas Toso",
    country: "アルゼンチン",
    region: "メンドーサ",
    grape: "MA/CS",
    color: "赤",
    type: "フル",
    vintage: "2022",
    alcohol: "14",
    price_bottle: 0,
    price_glass: 0,
    cost: 2800,
    stock: 0,
    ideal_stock: 0,
    supplier: "",
    storage: "",
    ai_explanation: "トソ家が愛した特別なテロワール『バランカス』の真髄。凝縮したプラムとトーストの香りが絶妙に溶け合い、心地よい渋みが食事の余韻を豊かに広げる、メゾンを象徴する一本です。",
    menu_short: "メゾンを象徴する最高バランス。トソの歴史を味わう赤。",
    pairing: "ボロネーゼ、鴨のロースト、ポルチーニのリゾット",
    sweetness: 1,
    body: 4,
    acidity: 3,
    tannins: 4,
    aroma_intensity: 4,
    complexity: 4,
    finish: 4,
    oak: 3,
    aroma_features: "プラム、トースト、スパイス、なめし革",
    tags: "代表作, 黄金バランス, エレガント",
    best_drinking: "2028",
    image_url: "https://drive.google.com/thumbnail?id=1aZb9-NY7eoBjWJ-XJSqFMV26ZZml1n-r&sz=w1200",
    visible: true
  },
  {
    id: "9309980",
    name_jp: "パスカルトソ アルタ マルベック",
    name_en: "Pascual Toso Alta Malbec",
    country: "アルゼンチン",
    region: "メンドーサ",
    grape: "マルベック",
    color: "赤",
    type: "フル",
    vintage: "2021",
    alcohol: "14.5",
    price_bottle: 0,
    price_glass: 0,
    cost: 5500,
    stock: 0,
    ideal_stock: 0,
    supplier: "",
    storage: "",
    ai_explanation: "アンデスの頂を思わせる孤高の存在感。厳選されたマルベックが、完熟した黒果実の奥にスミレの優雅さとタバコの複雑味を漂わせ、技術の粋を集めたリッチな余韻が長く続きます。",
    menu_short: "マルベックの気品を極めた、リッチで深みのある最高級赤。",
    pairing: "和牛のロースト、ラム肉のグリル、熟成コンテチーズ",
    sweetness: 1,
    body: 5,
    acidity: 3,
    tannins: 4,
    aroma_intensity: 5,
    complexity: 5,
    finish: 5,
    oak: 4,
    aroma_features: "スミレ、完熟プラム、タバコ、黒鉛",
    tags: "プレステージ, 濃厚, 高評価",
    best_drinking: "2030",
    image_url: "https://drive.google.com/thumbnail?id=181vD3lwyMnwDZ7rSHBH7qLZyf6X74rKF&sz=w1200",
    visible: true
  },
  {
    id: "9323775",
    name_jp: "マグダレナ・トソ",
    name_en: "Magdalena Toso",
    country: "アルゼンチン",
    region: "メンドーサ",
    grape: "MA/CS/SY",
    color: "赤",
    type: "フル",
    vintage: "2021",
    alcohol: "14.5",
    price_bottle: 0,
    price_glass: 0,
    cost: 12000,
    stock: 0,
    ideal_stock: 0,
    supplier: "",
    storage: "",
    ai_explanation: "31樽のみが厳選された、トソ家の至宝。カシスやバニラ、そして挽きたてのコーヒーのような芳醇なアロマ。圧倒的なエレガンスと究極の力強さが共存する、まさに「女王」の名にふさわしい傑作です。",
    menu_short: "時を止める圧倒的な余韻。トソが誇る究極のアイコン・ワイン。",
    pairing: "黒毛和牛の炭火焼き、トリュフが香る肉料理、特別な記念日に",
    sweetness: 1,
    body: 5,
    acidity: 3,
    tannins: 5,
    aroma_intensity: 5,
    complexity: 5,
    finish: 5,
    oak: 5,
    aroma_features: "カシス、コーヒー、杉、ダークチョコ",
    tags: "至宝, 究極の1本, 長期熟成",
    best_drinking: "2035",
    image_url: "https://drive.google.com/thumbnail?id=1N8SJ1Fc7pHYNl1atQNY-PT0x4GOGpUsj&sz=w1200",
    visible: true
  },
  {
    id: "9352204",
    name_jp: "パスカルトソ トロンテス",
    name_en: "Pascual Toso Torrontes",
    country: "アルゼンチン",
    region: "メンドーサ",
    grape: "トロンテス",
    color: "白",
    type: "辛口",
    vintage: "2025",
    alcohol: "13",
    price_bottle: 0,
    price_glass: 0,
    cost: 1600,
    stock: 0,
    ideal_stock: 0,
    supplier: "",
    storage: "",
    ai_explanation: "グラスに注いだ瞬間、バラの花びらやライチの魅惑的な香りが部屋を満たします。驚くほど華やかでありながら、後味はドライで清々しい、アルゼンチン独自の品種「トロンテス」の傑作です。",
    menu_short: "五感を刺激するアロマ。ライチとバラが舞う魅惑の辛口白。",
    pairing: "タイ料理（グリーンカレー）、パクチー料理、生春巻き",
    sweetness: 1,
    body: 2,
    acidity: 4,
    tannins: 1,
    aroma_intensity: 5,
    complexity: 3,
    finish: 4,
    oak: 1,
    aroma_features: "バラ、ライチ、ジャスミン、マスカット",
    tags: "アロマティック, 華やか, 魅惑の香り",
    best_drinking: "2027",
    image_url: "https://drive.google.com/thumbnail?id=1ODDPHiWeyFkIjszVRs9Hoh5APs5tCZ68&sz=w1200",
    visible: true
  }
];
